name: Generate Contribution 3D

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "Ahmed Abdelbaset"
          git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git pull

      - name: Generate 3D contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"

      - name: Check for changes
        id: git-check
        run: |
          if [[ -z $(git status -s) ]]; then
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi

      - name: Commit & Push
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git commit -am "Generate 3D on ${{ steps.date.outputs.date }}
          Co-Authored-By: Ahmed Abdelbaset <A7med3bdulBaset@gmail.com>
          "
          git push origin main
