name: Generate Contribution 3D

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
 # push: 
 #   branches: main


jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "Ahmed Abdelbaset"
          git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git pull

      - name: Generate 3D contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Has Changes
        id: changes # 1 true || 0 false
        uses: UnicornGlobal/has-changes-action@v1.0.11


      - if: steps.changes.outputs.changed == 1
        name: Commit & Push
        run: |
          git commit -am "Update Age on ${{ steps.date.outputs.date }}
          Co-Authored-By: Ahmed Abdelbaset <A7med3bdulBaset@gmail.com>
          "
          git push

      - if: steps.changes.outputs.changed == 0
        name: Already Up-to-date 
        run: echo "No changes to push"
