name: GitHub-Profile-3D-Contrib

on: [push]
  #schedule: # 03:00 JST == 18:00 UTC
  #  - cron: "0 18 * * *"
 # workflow_dispatch:
  #12
jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate 3D
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - name: Commit & Push
        run: |
          git config user.name Ahmed Abdelbaset
          git config user.email A7med3bdulBaset@users.noreply.github.com
          git add -A .
          git commit -m "Generate Contributions 3D"
          git push
