name: Update Age

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]

jobs:
  update-age:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        
      - name: Configure Git
        run: |
          git config --global user.name "Ahmed Abdelbaset"
          git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git pull

   
      - name: Update Age
        run: npm run update-age

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Has Changes?
        id: git-check
        run: |
          changes=$(git diff --name-only HEAD^ -- HEAD)
          if [[ -n $changes ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT

      - if: steps.git-check.outputs.changes == 'true'
        name: Commit & Push
        run: |
          git commit -am "Update Age on ${{ steps.date.outputs.date }}
          Co-Authored-By: Ahmed Abdelbaset <A7med3bdulBaset@gmail.com>
          "
          git push

      - if: steps.git-check.outputs.changes == 'true'
        name: Already Up-to-date 
        run: echo "No changes to push"
